---
- name: Установить WordPress, установить зависимости
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - php-curl
      - php-gd
      - php-xml
      - php-mbstring
      - wget
      - unzip
      - python3-pymysql
    state: present
    update_cache: yes

- name: Удалить дефолтную страницу Apache
  file:
    path: /var/www/html/index.html
    state: absent

- name: Скачать WordPress (tar.gz)
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Распаковать WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
    extra_opts: [ "--strip-components=1" ]

- name: Создать базу данных wordpress
  delegate_to: 192.168.1.126
  mysql_db:
    name: wordpress
    state: present
    encoding: utf8mb4
    collation: utf8mb4_general_ci
    login_user: root
    login_password: "MyRootPassword123!"

- name: Allow root login from 192.168.1.% hosts
  delegate_to: 192.168.1.126
  mysql_user:
    name: root
    host: "192.168.1.%"
    password: "MyRootPassword123!"
    priv: "*.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "MyRootPassword123!"

- name: Grant privileges to WordPress user
  delegate_to: 192.168.1.126
  mysql_user:
    name: wordpress
    host: "%"
    password: "StrongPassword123!"
    priv: "wordpress.*:ALL"
    state: present
    login_user: root
    login_password: "MyRootPassword123!"

- name: Настроить права на папку WordPress
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes

- name: Deploy wp-config.php
  copy:
    src: wp-config.php
    dest: /var/www/html/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Перезапустить Apache
  service:
    name: apache2
    state: restarted
