---
- name: Удалить Prometheus и Grafana
  apt:
    name:
      - prometheus
      - grafana
    state: absent
    purge: yes
  ignore_errors: yes

- name: Очистить конфиги Prometheus и Grafana
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus
    - /etc/grafana
    - /var/lib/grafana
    - /tmp/grafana.deb
