---
- name: Установить Prometheus
  apt:
    name: prometheus
    state: present
    update_cache: yes

- name: Развернуть конфиг Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644

- name: Перезапустить Prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes

- name: Скачать Grafana .deb
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana_10.4.1_amd64.deb"
    dest: "/tmp/grafana.deb"
    mode: '0644'

- name: Установить Grafana
  apt:
    deb: "/tmp/grafana.deb"

- name: Запустить Grafana
  service:
    name: grafana-server
    enabled: yes
    state: started
