---
- import_tasks: install_mysql_master.yml
  tags:
    - install
    - install_mysql
    - install_mysql_master
  when: "'db_master' in group_names"

- import_tasks: install_mysql_slave.yml
  tags:
    - install
    - install_mysql
    - install_mysql_slave
  when: "'db_slave' in group_names"

- import_tasks: install_mysql_replication_master.yml
  tags:
    - install
    - install_mysql
    - install_mysql_replication
    - install_mysql_replication_master
  when: "'db_master' in group_names"

- import_tasks: install_mysql_replication_slave.yml
  tags:
    - install
    - install_mysql
    - install_mysql_replication
    - install_mysql_replication_slave
  when: "'db_slave' in group_names"

- import_tasks: install_mysql_backup.yml
  tags:
    - install
    - install_mysql
    - install_mysql_backup
  when: "'monitoring' in group_names"

- import_tasks: restore_mysql.yml
  tags:
    - restore
    - restore_backup
  when: "'monitoring' in group_names"

- import_tasks: delete_mysql_master.yml
  tags:
    - delete
    - delete_mysql
    - delete_mysql_master
  when: "'db_master' in group_names"

- import_tasks: delete_mysql_slave.yml
  tags:
    - delete
    - delete_mysql
    - delete_mysql_slave
  when: "'db_slave' in group_names"
